# Generated by Django 4.1.1 on 2022-09-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nome',
            new_name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
