# Generated by Django 4.1.1 on 2022-09-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_nome_user_name_user_age_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
    ]
